### ISSUE TITLE
Need to add image in center

### ISSUE THREAD

**Issue by kumarkk** [szugyi/Android-CircleMenu#10]
Need to add an image in center of circle.

**Comment by szugyi** [comment]
You can do it using the circleBackground attribute of the CircleLayout.
There is a sample demonstrating it: https://github.com/szugyi/Android-CircleMenu/blob/master/CircleMenuSample/res/layout/sample_with_background.xml

**Comment by payamm67** [comment]
hi , i need to add an image in center of circle too , but not exit circleBackground attribute in the CircleLayout.

**Comment by szugyi** [comment]
@payamm67 You can add an ImageView separately under the CircleLayout, just wrap it around a FrameLayout, or any LayoutGroup you need to use to best suit your needs.
