### ISSUE TITLE
Random menu item selection through Button with rotating animation.

### ISSUE THREAD

**Issue by jjvargas** [szugyi/Android-CircleMenu#11]
I would like to have a button that makes the Circle Menu rotates de-accelerating until it chooses a menu item randomly with no touch involved, Can you please give me some hints on where to modify the code?

**Comment by szugyi** [comment]
I think you could use the private void animateTo(float endDegree, long duration) method of the CircleLayout. Make it public. 

- In your Activity, on the Button click, you could randomly choose one of the menu items where the animation will end. 
- Calculate the destenation degree
- Add 360 degrees a few times, so the menu item will make more circles before it stops.
- You can also randomly change the duration of the animation, adding some more sense of randomness.
- Then call the animateTo method with these random numbers.
