### ISSUE TITLE
Not able to stop the selected child self rotation

### ISSUE THREAD

**Issue by prashanthd** [szugyi/Android-CircleMenu#13]
Hi,
How to stop the selected child view self rotation. I want circle menu to be rotatable but not the  child which is selected. I gone through the circlelayout class  but not able to figure out the thing.

**Comment by szugyi** [comment]
It is only an Animation which is applied on the Child in the sample application. If you remove the onRotationFinished event listener from the CircleLayout, then it will not rotate the child when it is selected.

**Comment by prashanthd** [comment]
Thanks for replay.
