### ISSUE TITLE
Is it possible to create a layout like this with custom check boxes or radio button 

### ISSUE THREAD

**Issue by manishpatidar** [szugyi/Android-CircleMenu#15]
![mylayout](https://cloud.githubusercontent.com/assets/4478996/12034237/3e2de36c-ae54-11e5-80f4-0855587187ed.png)

**Comment by szugyi** [comment]
Right now it is not possible, since the CircleLayout is relying on
containing CircleImageViews. We should keep track of the current rotation
vaues of the childs inside the CircleLayout itself to be able to use any
kind of View inside the layout. If you can change it like this, please do
it and issue a pull request. Otherwise I will take a look at it later.

**Comment by manishpatidar** [comment]
szugyi it is not necessary that outer circle should rotate all I want is that Text View and check boxes  should be aligned at a particular place in that circle.Please, suggest suggest a way.

**Comment by szugyi** [comment]
@manishpatidar I have created a new branch called any-view, you can see it here: https://github.com/szugyi/Android-CircleMenu/compare/any-view

You can see a new sample called Any view, which shows that now RadioButtons, or any other Views can be included inside the CircleLayout. I hope you can create the functionality you want with this version.

**Comment by szugyi** [comment]
@manishpatidar Were you able to use this version for your needs?

**Comment by adelriosantiago** [comment]
@szugyi Thanks for this branch! It is exactly was I was looking for, I would really like to see it integrated to master *-CircleImageView are like ImageView anyways-* and now we can create more complex menus.

**Comment by szugyi** [comment]
@adelriosantiago In the following few days I will do that, but I want to make sure everything works fine. I am also working on migrating to gradle/Android Studio and uploading the library to maven central.

**Comment by adelriosantiago** [comment]
On the next days I will add radio buttons and checkboxes to a new menu tab on the CircleMenuSample on the fork https://github.com/adelriosantiago/Android-CircleMenu, I migrated the project to Gradle (not sure if my .gitignore is correct but it seems to work)

**Comment by szugyi** [comment]
@adelriosantiago I have just merged the any-view branch into master, and migrated to Android Studio also. I am about to upload the lib to mavencentral, to make it available via gradle.

**Comment by szugyi** [comment]
@adelriosantiago The lib is now available via Gradle: compile 'com.github.szugyi:Android-CircleMenu:1.0.0'
