### ISSUE TITLE
Is it possible, item's drawble larger than another after roating.

### ISSUE THREAD

**Issue by reza007** [szugyi/Android-CircleMenu#17]
Hello,
Is it possible the selected item going larger than another items drawable?

**Comment by szugyi** [comment]
Do you want to make the currently selected item to appear bigger than the others?
If yes, it should be possible with the any-view branch, which will be merged into the master, once I have finished testing it.
You can find the branch here: https://github.com/szugyi/Android-CircleMenu/tree/any-view

**Comment by reza007** [comment]
yes, but when change image resource for view (bigger than the other) onRotationFinished, the other views change size and View's image size are same size of new image.

**Comment by szugyi** [comment]
how do you change the drawable?

**Comment by reza007** [comment]
((CircleImageView) view).setImageResource(R.drawable.circle_active1);

**Comment by szugyi** [comment]
so when you change the resource for only the selected item to a bigger image, all the other images get bigger, not only the one which is the selected?

**Comment by reza007** [comment]
yes , exactly.

**Comment by szugyi** [comment]
I can reproduce the problem, I am trying to fix it.

**Comment by reza007** [comment]
Thanks my Dear.

**Comment by szugyi** [comment]
@reza007 I have updated the CirlceLayout. Now the sizes of each child is handled separately, so now it is possible to set the selected child to be bigger than the others. Make sure you are using the version on the any-view branch, which will be merged into the master, after i add a few more minor upgrades.
