### ISSUE TITLE
Set width/heigt for icon/image

### ISSUE THREAD

**Issue by MrLoveQD** [szugyi/Android-CircleMenu#18]
Hi.
Thanks you for your library.
It's very great.
I have a problem.
How do i can set width/heigt for icon/image ?

**Comment by szugyi** [comment]
Sorry, I did not get a notification about this new issue.
With the new version now it is possible to have Views with any size inside the CircleLayout. From now on you can use any kind of Views as a child also. Note that I have migrated the project to use Android Studio. I am bout to upload the lib to mavencentral also, to make it available via gradle.
