### ISSUE TITLE
setOnLongClickListener for remove circle child

### ISSUE THREAD

**Issue by reza007** [szugyi/Android-CircleMenu#19]
Thanks szugyi for share,
for remove child of circle ,need set On long click for child, is it possible?
generally, is it possible to remove child dynamically?

**Comment by szugyi** [comment]
Hey @reza007!
Yes, in general it is possible to remove and add child views dynamically. It is a good point, so i will create a sample to demonstrate it today. Unfortunately long clicks are not supported. If you would set a long click listener for a child it would consume touches, so it would break the functionality of the CircleLayout. 

I will take a look, and think about how could I implement it easily, but i cannot promise anything. Try to avoid using long click, or try to implement is yourself if avoiding it is not feasible. As I was experimenting with LongClick, it looks goofy when you see the child moving while you are "long clicking" it, so I would suggest not to use it anyway, only with non-rotating CircleLayout. If you have a non-rotating CircleLayout set up, then I think you should have no problem using LongClick listeners on your child Views.

**Comment by szugyi** [comment]
@reza007 Just pushed a new version to the develop branch, with a new sample, which demonstrates the ability to add and remove views. I am improving this function now so when you remove a view it will update the positions of the views better.

**Comment by reza007** [comment]
@szugyi 
I am glad to hear, thank you very much.

**Comment by szugyi** [comment]
@reza007 
I have finished updating the Layout to handle adding and removing views properly. It is on the development branch at the moment, but hopefully tomorrow I can merge it into the master and release a new version to maven central.
