### ISSUE TITLE
Set background for circleMenu

### ISSUE THREAD

**Issue by MrLoveQD** [szugyi/Android-CircleMenu#21]
Hi.
Thanks you so much for this library. It's great!
How do i do set background for it ? like as this image:
http://i.imgur.com/88tmKXS.png
Background color and icon of each item will set from programmatically (from a list colors and icon).

Please help me.

**Comment by szugyi** [comment]
Hi @MrLoveQD,
Currently you are not able to create something like this with the CircleLayout. What you can do is setting a background drawable using the circle:circleBackground="@drawable/bg" which will scale it to the size of the Layout, but it will not rotate with the icons. You would need to override the onDraw method of the CircleLayout to make it rotate. The angle variable of the CircleLayout tells you the current value of the rotation of the child elements.
