### ISSUE TITLE
Question - Move a certain child to first position

### ISSUE THREAD

**Issue by dmsherazi** [szugyi/Android-CircleMenu#22]
How can I programatically move a certain child to the first position?

**Comment by szugyi** [comment]
Right now it is not possible, but there is the `private void rotateViewToCenter(View view)` method which you could make public, so you can call it with the given child view. But if you have a few days to wait, I can make this change and publish a new version to maven central, so you just need to use the new release in gradle. I will let you know when the update is available.

**Comment by dmsherazi** [comment]
Thanks , 

I managed to do it by cloning and modifying this repo.

**Comment by szugyi** [comment]
Thanks, 
I have pulled your pull request, and made a new release to maven central with it, with version number 1.1.1.

**Comment by dmsherazi** [comment]
Thanks
