### ISSUE TITLE
Hide a half circlemenu 

### ISSUE THREAD

**Issue by toptuto** [szugyi/Android-CircleMenu#25]
how can i hide the circle in a half in the bottom of the screen , thanks

**Comment by szugyi** [comment]
@toptuto You could use a negative margin on the bottom of the CircleLayout to hide half of the view.

**Comment by toptuto** [comment]
Thank you very much , it's work !!

**Comment by szugyi** [comment]
Great to hear it :)

**Comment by bjccoronel** [comment]
Hi szugyi, additional question on this, since the circle is half visible, if i have only 4 items? can i squeeze those only in the visible part of the circle?

**Comment by szugyi** [comment]
@barryjohncoronel There is currently no way to do this

**Comment by bjccoronel** [comment]
Thanks. :)

**Comment by szugyi** [comment]
@barryjohncoronel Actually, if you do not want to make the CircleLayout rotating, than you might be able to add 4 additional views, which you will hide, so those could be anything.
