### ISSUE TITLE
click to item

### ISSUE THREAD

**Issue by toptuto** [szugyi/Android-CircleMenu#26]
I have downloaded ur source code and then i click to the item and it spin to the firstChildPosition , but i cant find where u use this code in your source code  .  THanks

**Comment by szugyi** [comment]
Take a look at the onSingleTapUp and the onTouchEvent methods in the CircleLayout class. Those are the methods which call the rotateViewToCenter method with the selectedView to make sure the tapped view is rotated to the firstChildPosition.

**Comment by toptuto** [comment]
i have seen those method already but i still wonder where r u use those
method in your sample folder ??

**Comment by szugyi** [comment]
Why would I use them directly in the sample folder? The point is that the
CirleLayout takes care of the rotation of the child Views, and you can do
what you like when the rotation finishes, or one of the children is
selected.

How would you like to use it?

**Comment by toptuto** [comment]
sorry but if u not use them in your sample folder then how you can make the item rotate to firstChildPosition when you click to item ??

**Comment by szugyi** [comment]
The CircleLayout is responsible for it. It is not inside the sample, but the sample is using the library containing the CirlceLayout. Since the items are placed inside the CirlceLayout, the Touch events can be processed by it.

**Comment by toptuto** [comment]
But it's not work for me , when i click to the button which was the item of
the Circlelayout , it's still there
Vào 10-04-2016 21:33, "Csaba Szugyiczki" <notifications@github.com> đã viết:

**Comment by szugyi** [comment]
If you are using the Button inside the CircleLayout, it is possible that the Button is consuming the touch event, and the CircleLayout does not know about it. Try using an ImageView instead, or disable the Button.

**Comment by toptuto** [comment]
it's work ! Thank you so much !
