### ISSUE TITLE
Radius 

### ISSUE THREAD

**Issue by tohai666** [szugyi/Android-CircleMenu#27]
Hi , 
Your library is very awesome . 
I have 2 question. 
Can i increase the radius of the CircleLayout ? If yes , how ? 
How can i make the item bigger when that item is at firstChildPosition ? 
Thanks

**Comment by szugyi** [comment]
Hi,
Right now you can increase the radius only by changing the code of the CircleLayout itself. It determines the radius inside the onLayout method on line 340.
Making bigger an item at first child position might be done in the onItemSelected callback. You can see example usage of the callback in the SampleActivity. If you want to make it bigger depending on how close it is to the dirstChildPosition, then once again, you will need to change the code of the CirlceLayout itself inside the setChildAngles method, which calculates the rotation of all child views, and sets their position accordingly.

**Comment by tohai666** [comment]
ohh thanks !! 
I hope you can update the library that we can change the radius directly in XML file , that will be great ! 
Thanks again .

**Comment by szugyi** [comment]
New version 2.0.0 is now out, and makes it possible to set the radius of the circle.
