### ISSUE TITLE
Child icons placing outline of the image . How to reduce the radius 

### ISSUE THREAD

**Issue by ananthDev** [szugyi/Android-CircleMenu#28]
Thanks for the Wonderful Library ..
I have problem diffcult to find the solution .. 

Problem is Child Icons are not clear visible. It place end of ViewGroup
How to reduce the radius and show the icon clear visible to center of  border/stroke. 
![screenshot_2016-06-01-17-11-43](https://cloud.githubusercontent.com/assets/5661088/15708501/6bac267c-281c-11e6-8a3a-9792e682d826.png)

and other question it is possible to rotate  the background image based upon ACTION_MOVE 
Thanks in Advance

**Comment by szugyi** [comment]
Right now it is not possible to set the radius of the background image or the child icons.
I am planning to make it possible via setters and xml attributes in the future, but not in the near future unfortunately. 

You can override the radius calculation directly in the onLayout method if you really need it:
https://github.com/szugyi/Android-CircleMenu/blob/master/circlemenu/src/main/java/com/szugyi/circlemenu/view/CircleLayout.java#L340

 or you can use your own background by placing a view underneath the CircleLayout.

**Comment by ananthDev** [comment]
Thanks Szugyi for quick response , 

I used background for CircleLayout 

 ```
<com.szugyi.circlemenu.view.CircleLayout
        android:id="@+id/circle_layout"
        android:layout_width="250dp"
        android:layout_height="250dp"
        android:layout_above="@+id/selected_textView"
        android:layout_gravity="center_horizontal"
        android:background="@drawable/bg"
        circle:firstChildPosition="East"
        circle:isRotating="true">
```

Added 

> radius += 40;

```
    @Override
    protected void onLayout(boolean changed, int l, int t, int r, int b) {
        int layoutWidth = r - l;
        int layoutHeight = b - t;

        radius = (layoutWidth <= layoutHeight) ? layoutWidth / 3
                : layoutHeight / 3;
        radius += 40;
        Log.e("onLayout", "radius: " + radius);
        circleHeight = getHeight();
        circleWidth = getWidth();
        setChildAngles();
    }


```
![screenshot_2016-06-01-17-40-35](https://cloud.githubusercontent.com/assets/5661088/15709227/37356570-2821-11e6-87ab-614272cd0b99.png)

Is that Right ?

**Comment by szugyi** [comment]
Well, hard coding pixel values is dangerous, you could play with increasing the divisor value (which is right now 3). Anyway yes, right now this is the only way you can align the background and the icons.

**Comment by ananthDev** [comment]
You right.. due to pixel value In Config change .. it showing wrong place..

So played a little changes in setChildAngles ()

```
float gap=   radius - TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 18, getResources().getDisplayMetrics());
            childWidth = child.getMeasuredWidth();
            childHeight = child.getMeasuredHeight();
            left = Math
                    .round((float) (((circleWidth / 2.0) - childWidth / 2.0) + gap
                            * Math.cos(Math.toRadians(localAngle))));
            top = Math
                    .round((float) (((circleHeight / 2.0) - childHeight / 2.0) + gap
                            * Math.sin(Math.toRadians(localAngle))));
```

I tested in sw360 and sw320 device .. Both showing same.

Is that right for future use?

**Comment by szugyi** [comment]
It still feels a little hacky, but it might be good for your situation. I will try to come up with something more robust and customizable later.

**Comment by jxc02** [comment]
Hey @ananthDev how did you remove the red background of the icons
circle:circleBackground="@null"    isn't working

**Comment by szugyi** [comment]
Hey @jxc02,
circle:circleBackground="@null" sets the background of the whole circleLayout. For the individual menu items, you can set the background individually. In the sample you can modify the background for them in the menu_items.xml. Source: https://github.com/szugyi/Android-CircleMenu/blob/master/sample/src/main/res/layout/menu_items.xml

**Comment by jxc02** [comment]
Yes I just found that
Wow you reply fast. Thanks a lot!

**Comment by szugyi** [comment]
New version 2.0.0 is now out, and makes it possible to set the radius of the circle.
