### ISSUE TITLE
Adding Item in the center

### ISSUE THREAD

**Issue by AhmedWarreth** [szugyi/Android-CircleMenu#29]
Hello! 
Great library! I ported some of the code to C# and I'm using it in Xamarin.

One question I have is how I would add an item in the middle?  I want an item in the middle with 4 buttons around it.

Any pointers would be appreciated! 

Thanks again.

**Comment by szugyi** [comment]
Dear Ahmed,

I guess you could place a “placeholder” item in the middle, and place the 4 buttons around it. It does not have to be within the CircleLayout item.

Happy coding,
Csaba
