### ISSUE TITLE
Inside the layout scrollview

### ISSUE THREAD

**Issue by fhsh168** [szugyi/Android-CircleMenu#3]
the code：

<ScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent" > 

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content" >

            <com.szugyi.circlemenu.view.CircleLayoutMenu
                android:id="@+id/main_circle_layout"
                android:layout_width="fill_parent"
                android:layout_height="300dp"
                android:layout_gravity="center_horizontal"
                circle:firstChildPosition="South"
                circle:isRotating="true"
                circle:rotateToCenter="true"
                circle:speed="75" >

When the rotation animation is not good

**Comment by szugyi** [comment]
@fhsh168 Could you be more specific please?
When the RelativeLayout parents height is set to "wrap_content" then the rotation animation does not work?
