### ISSUE TITLE
Child items rotates

### ISSUE THREAD

**Issue by Manoharlsn** [szugyi/Android-CircleMenu#32]
Thanks for great library,
when click on the child items its rotates, when can we stop the child items rotates in onItemClickListner.

**Comment by szugyi** [comment]
Remove the code which starts the animation of the selected view in the onRotationFinished callback to get rid of the rotation animation.

**Comment by Manoharlsn** [comment]
But when click on the child item it rotates how can we stops it child event in every child item

**Comment by szugyi** [comment]
Ok. Now I think I understand the question. Set the isRotating xml attribute of the CircleLayout to false, to stop rotation of the child views. You can see an example of it here: https://github.com/szugyi/Android-CircleMenu/blob/master/sample/src/main/res/layout/sample_no_rotation.xml

**Comment by Manoharlsn** [comment]
I want to make rotates flase circle menu not in circlurlayout

**Comment by szugyi** [comment]
I'm afraid I do not understand your question.

**Comment by Manoharlsn** [comment]
Thanks a lot for replaying me
What my intension is when onclick on child item its rotates and the first child position  will have the onitemclick event but we want  child item click we need here click event.

**Comment by szugyi** [comment]
In my first answer I have told you how to prevent to roatation of the child item, when the rotation of the menu items is finished. The second answer tells you hot to prevent the whole layout from rotating any of the child items. I do not know what other rotation you might want to stop. Please make a video or screenshots of the behaviour you want to change.

**Comment by Manoharlsn** [comment]
when click on the child item it comes to firstchildposition who to stop this rotation.

**Comment by szugyi** [comment]
This example works just how you want it: https://github.com/szugyi/Android-CircleMenu/blob/master/sample/src/main/res/layout/sample_no_rotation.xml

**Comment by Manoharlsn** [comment]
we need rotation but when  click on the child item no need to rotate.

**Comment by szugyi** [comment]
Then you have to comment out the 629th line in the CircleLayout, and use the library as your own customized module inside your application. https://github.com/szugyi/Android-CircleMenu/blob/master/circlemenu/src/main/java/com/szugyi/circlemenu/view/CircleLayout.java#L629

**Comment by Manoharlsn** [comment]
Thanks a lot for your support.
