### ISSUE TITLE
Caption under each CircleImageView

### ISSUE THREAD

**Issue by jxc02** [szugyi/Android-CircleMenu#33]
Is it possible to add a caption under each menu item like in attached image?
![whatsapp image 2016-09-13 at 8 26 48 pm](https://cloud.githubusercontent.com/assets/18242568/18484304/88151e42-79f0-11e6-8f9c-b17909db52cd.jpeg)

**Comment by szugyi** [comment]
You can use whatever View you like, so yes it is possible. Try to add TextViews inside the CircleLayout, and set the icons as the drawableTop attribute of the TextViews.
