### ISSUE TITLE
Similar implementation for iOS

### ISSUE THREAD

**Issue by ivansnek** [szugyi/Android-CircleMenu#34]
Awesome library, I'm trying to do the same on iOS(Swift), do you know something similar?

**Comment by szugyi** [comment]
Hey @ivansnek,
I do not know about any similar library for iOS.
If you start to implement something like this, tell me and I might be able to give you tips.

**Comment by drturing** [comment]
Very nice. Thank you.
@ivansnek For iOS, checkout https://github.com/Ramotion/circle-menu

**Comment by ivansnek** [comment]
@szugyi thanks man, I've been working with that for the last couple days, and only acomplish a simple implementation :)

**Comment by ivansnek** [comment]
@drturing oh thanks, I've allready see that and its really good, but in my team(Android devs) they use this (Android-CircleMenu) library and the client wants a similar menu on the iOS app, but thanks for passing by and leave a tip ( sorry about my english)

**Comment by szugyi** [comment]
@ivansnek When I started this lib it took me more than a week to implement all the basic functionalities. Do it step by step and it will come together in the end. 
Happy coding!
