### ISSUE TITLE
implement a central icon

### ISSUE THREAD

**Issue by drturing** [szugyi/Android-CircleMenu#35]
Hi, Thank you for this wonderful & super useful widget.
 Would it be possible to implement an icon in the center. When the icon is clicked, the menu would pop-up? At that point the icon changes to a cancel icon. When that icon is clicked again, the circle menu closes. You can see an example in iOS here. https://github.com/Ramotion/circle-menu

Ideally, the central button could be placed any where (say center point of the North-East quadrant), and if the radius was set to that half the size of the quadrant, the menu would show up in that North-East quadrant

Thanks in advance.

**Comment by szugyi** [comment]
Hi @drturing,
I think you can create a similar animation using Property animations on the CircleLayouts radius and visibility properties. The extra middle icon could be a separate ImageView in the center of the view. You might be able to align it there using a RelativeLayout as a wrapper around the CircleLayout.

**Comment by drturing** [comment]
Thanks for your prompt response.
I'm no android programming expert. i've used layout files before.  I was just wondering if you could share some sample code, or extend the code for others to use. 

Thanks again for your contributions

**Comment by szugyi** [comment]
I'm sorry, right now I do not have enough time to implement such functionality.

**Comment by szugyi** [comment]
@drturing I have just found the Android port of this lib: https://github.com/Hitomis/CircleMenu
