### ISSUE TITLE
How to draw lines between all circle menu ?

### ISSUE THREAD

**Issue by Rupesh2Singh** [szugyi/Android-CircleMenu#41]
Hi szugyi,
how to set a image/button in center of the circular menu and can we draw a line that is connected with other menu item in circle.

**Comment by szugyi** [comment]
Hi Rupesh,
If you put the CircleLayout inside a RelativeLayout, you can put a button in the center of it. To draw lines to every menu item, you would need to update the onDraw method of the CircleLayout.

**Comment by Rupesh2Singh** [comment]
Hi Szugyi,
Thanks for your valueable answer but still i had a doubt if i'm using your gradle dependency of CircleMenu then how to implement CircleLayout inside a RelativeLayout. could you provide any sample code to implement or any reference would be greateful.

**Comment by szugyi** [comment]
If the RelativeLayout is set to wrap the CircleLayout you can put a button on top of the center of the CircleLayout like this:
`
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:circle="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    tools:context=".SampleActivity" >

    <com.szugyi.circlemenu.view.CircleLayout
        android:id="@+id/circle_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_above="@+id/selected_textView"
        android:layout_gravity="center_horizontal" >

        <include layout="@layout/menu_items" />
    </com.szugyi.circlemenu.view.CircleLayout>

    <Button
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true" />

</RelativeLayout>`

**Comment by Rupesh2Singh** [comment]
Thanks Szugyi as you have mentioned it works fine to set image in center of circlemenu but i still stuck in drawing the line in circularMenu items and there is no onDraw method in the CircleLayout.java class please help me to implement and it be greateful for me.

**Comment by szugyi** [comment]
It is not an easy task to do. There is no onDraw, since the CirclaLayout originally just deals with the layout process of its children. You would need to implement this functionality yourself. The angle of each item can be found in the Tag property of each individual item. Sorry, I can not implement it for you, as this function is not required for the basic functionality of the layout.

**Comment by Rupesh2Singh** [comment]
Thanks a lots Szugyi for your valueable suggestion.
