### ISSUE TITLE
Do something when the wheel rotating

### ISSUE THREAD

**Issue by matolaypal** [szugyi/Android-CircleMenu#43]
Hi, 
I'm really graceful for this awesome work. Thanks a lot!

However I have a question. So, I want to play a music, when the wheel is rotating. That's okay I can check the isRotating methods return value, but how can play music for ever, when the wheel rotating?
I need an Async task or maybe you have a better idea?
(I used this layout via gradle, so I don't exactly change the source code, if it possible.)

Best regards from a Hungarian android lover! :wink:

**Comment by szugyi** [comment]
Hi Pál,

In this case I think you can use the `setOnRotationFinishedListener` method with which you can receive the event when the `CircleLayout` stopped rotating. This way you do not have to poll the state, but your code will be notified when the rotation stopped. The tricky part will be to find out when the rotation starts. Currently it is not supported by the library. 

If you do not want to customize the code you might be able to set an `OnTouchListener` on the `CircleLayout` and tell if the layout has been touched, hence it is likely it started rotating, but you might need to configure it to only change state if the movement of the touch is above a certain threshold. Remember to return false from the listener to not prevent other listeners to work properly.

Happy coding!
Best wishes from Budapest! ;)

**Comment by matolaypal** [comment]
Hi,

oh really! I forget the touch listener.. Thanks for helping and fast answering!
(Yeah, the music stopping isn't a question. I knew it. Sorry for the inaccurate expression.)
Have a good day!
