### ISSUE TITLE
hello dear

### ISSUE THREAD

**Issue by BongJaeChoi** [szugyi/Android-CircleMenu#48]
Thanks for Library.

I just want to show appreciation.

Thanks to you, I was able to develop the roulette function correctly.
![kakaotalk_2017-11-30-14-34-37_photo_49](https://user-images.githubusercontent.com/8946333/33415697-9e9783b0-d5db-11e7-863c-9b539ebeef28.png)

**Comment by szugyi** [comment]
@BongJaeChoi Awesome! Glad you found it useful.
