### ISSUE TITLE
Change the Diameter of the Circle ?

### ISSUE THREAD

**Issue by AruLNadhaN** [szugyi/Android-CircleMenu#5]
How can i change the Diameter of the Circle in the CircleMenu ?

**Comment by szugyi** [comment]
@AruLNadhaN 
Sorry for the late response.
You can manipulate the radius of the circle, and the size of the menus in the onLayout method starting on the 255th line.

radius = (layoutWidth <= layoutHeight) ? layoutWidth / 3
				: layoutHeight / 3;
right now the radius is 1/3 of the smallest side of the layout, so the diameter is 2/3 of it.
