### ISSUE TITLE
How to set left/right margin and increase size of Center image of circle at top position??Other parts will remain little on circle layout.

### ISSUE THREAD

**Issue by rohantalukder** [szugyi/Android-CircleMenu#51]
Like this .. 
![key_icon](https://user-images.githubusercontent.com/11829221/35664364-01b4afe4-074c-11e8-9918-908355d00671.png)

**Comment by szugyi** [comment]
You could use the `OnItemSelectedListener` to animate the view that is currently selected.

**Comment by rohantalukder** [comment]
i dont want to animate.I want to increase width height and margin of center image at first child position.

**Comment by szugyi** [comment]
Just simply change the width and height of that view then. to change the margin dynamically you will have to set new LayoutParams for the view.

**Comment by szugyi** [comment]
You receive the view in the center in the onItemSelected callback.
see: https://github.com/szugyi/Android-CircleMenu/blob/afd2df796aaa8207e1ecd94179b2d1e3af4d7cd1/sample/src/main/java/com/szugyi/circlemenusample/SampleActivity.java#L68

**Comment by rohantalukder** [comment]
//enlarge middle icon
    public void enLargeCenter(CircleLayout layout,View circle_view){

        final int childCount = layout.getChildCount();
        for (int i = 0; i < childCount; i++) {
            View v = layout.getChildAt(i);
            v.setScaleX(1f);
            v.setScaleY(1f);
        }
        circle_view.setScaleX(3f);
        circle_view.setScaleY(3f);

        LinearLayout.LayoutParams params = new LinearLayout.LayoutParams(300, 300);
        params.setMargins(500,500,500,500);
        circle_view.setLayoutParams(params);

    }


only middle icon get increase in size but margin dont add..this is used under onitemselected method.

**Comment by szugyi** [comment]
Ahh yes, the layout does not support margins currently, since it is not clear how those should adjust the positioning of the views. You could try wrapping your views in FrameLayout-s and then adding padding on the FrameLayout to achieve similar visual effect.

**Comment by rohantalukder** [comment]
"it is not clear how those should adjust the positioning of the views " what this means ??
i want center image bigger and margin it from other images and other images will remain smaller.Thats it.
And U mean when adding item/imageview on circle layout before that i will wrap that on frame layout,right??

**Comment by szugyi** [comment]
Yes, wrap the views that you add to the CircleLayout inside a FrameLayout. If these are simple ImageView-s then wrap them inside a FrameLayout, and than use padding on the FrameLayout to "imitate" having margins on the images

**Comment by rohantalukder** [comment]
ok i have understood.
But i just want center image to be margined others will not.
Only center image will have margin left right,others image will not get any margin.they will be as default.

**Comment by szugyi** [comment]
Yeah, you will need to reset the other images to have the default settings
