### ISSUE TITLE
Zoom image item during rotate

### ISSUE THREAD

**Issue by strictlad** [szugyi/Android-CircleMenu#8]
Thank you for your project. It's magic.
But I'd like to zoom out and zoom in image item gradually based on its angle when rotate.
How can I solve my problem?
See your answer soon.
Thanks, again.

**Comment by szugyi** [comment]
I think you have to implement this yourself. I guess you have to modify the onLayout method on line 289, where the child views are put out. Try increasing childWidth and childHeight based on the childs angle.

"child.layout(left, top, left + childWidth, top + childHeight);"

**Comment by strictlad** [comment]
Thanks @szugyi your suggestion.
I modified some function in your code, and it worked well, at least as I expected.

**Comment by szugyi** [comment]
@strictlad I'm glad it worked for you!
Happy coding!
