### ISSUE TITLE
How to add title below each image child?

### ISSUE THREAD

**Issue by strictlad** [szugyi/Android-CircleMenu#9]
Hi, @szugyi 
I'm glad after zooming child views when rotate successfully. And now, I want to add a title or a textview below each image child. I tried to make a customview extending RelativeLayout (contains an imageview and a textview) but the height and width childs are not fill. Do you have any ideas for me?
Thank you very much.

**Comment by szugyi** [comment]
Sorry for the late reply,
Try to use TextViews, as childs in the CircleLayout. Set the image you want for each TextView using the drawableTop attribute of the TextViews. I think it should work that way.
